### ISSUE TITLE
Feature Request: show count on map

### ISSUE THREAD

**Issue by cedricve** [githublemming/CloudTrailViewer#5]
Mark, it can be useful to also show the count also on the map. Don't think its that much work to implement? I think it would be helpful, to see to most active continents.

E.g.

![screen shot 2016-12-23 at 10 48 35](https://cloud.githubusercontent.com/assets/1546779/21451217/a2462390-c8fd-11e6-90ea-76942858426b.png)

**Comment by haskins-io** [comment]
I think I'm restricted to the overlay functionality of leaflet / openstreetmap to what I can do here. I could add the count easily enough to the label when a marker is clicked.

I will have another read of the relevant documentation to see if any changes have been made since I implemented that feature.

**Comment by haskins-io** [comment]
HI Cédric,

I've created a new release (v2.6.6) that I believe covers the functionality that you have asked for. When you get time have a look at it and tell me what you think

Mark

**Comment by cedricve** [comment]
Perfect! Works like a charm 👍  Thank you
