### ISSUE TITLE
Load log files recursively

### ISSUE THREAD

**Issue by douglasheld** [githublemming/CloudTrailViewer#9]
Start state: Have an s3 bucket with files in directory format:
bucket/region/year/month/day/files.json.gz

Goal: load a year's worth of logs from a region

Steps to reproduce:
1. Click on "Cloud open" button
2. Select bucket
3. Select region
4. Select year
5. Click on "Load"

Expected results
Load will recursively find and download objects within the selected node

Actual results
The "Load" button is greyed out until I select a year, month and day. And then select one or more files.

**Comment by haskins-io** [comment]
Hi,

this is actually expected behaviour.

If you were to try and load all the files for your account for a year, there is a very good chance that the application will run out of memory, depending on how active your account is. Currently the application is aimed at either
* completely loading a couple of hours, or possibly days, again  base on how active your account is
* scanning hundreds (even thousands) of file looking for matches and only loading those events into memory.

If you wanted to load all the events for a year:
* Open the dialog
* Click the filter button
* Choose the appropriate Account filter and enter your account id
* The you should be able to navigate through your bucket and select a folder.

Mark

**Comment by haskins-io** [comment]
Hi,

I've just released a new Alpha version of the application that does not store the data in memory, but in a lucene backend. This might be more suitable for your needs.

If you are interested give it a go, you can get it from here : https://github.com/githublemming/CloudTrailViewer/releases/tag/3.2.0-alpha

Mark

**Comment by haskins-io** [comment]
I've had no response so I'm closing the ticket
